name: Deploy Cine-Delices to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      # 4️⃣ Build le projet Vite
      - name: Build project
        run: npm run build
        working-directory: ./frontend

      # 5️⃣ Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_DEPLOY }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages
