name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Récupérer le code
      - uses: actions/checkout@v4

      # 2️⃣ Installer Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3️⃣ Installer les dépendances et builder depuis le dossier frontend
      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build

      # 4️⃣ Publier le dossier dist sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
